services:
  - type: web
    name: whatsapp-webhook
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node webhook-server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_VERIFY_TOKEN
        value: your_secure_verify_token_here
